application:
  name: Lania
  icon: Textures/Pong_Icon.png
  main_scene: Scenes/Main.yml
  command_line_on_start: false
application_window:
  title: Pong
  width: 853
  height: 480
  fullscreen: false
  resizable: false
  maximized: false
  rendering_api: sdl_2
  target_fps: 60