application:
  name: Lania
  icon: Textures/Horizontal_Environment.JPG
  main_scene: Scenes/Main.yml
  command_line_on_start: false
application_window:
  title: Lania Debug
  width: 853
  height: 480
  fullscreen: false
  resizable: true
  maximized: false
  rendering_api: sdl_2
  target_fps: 60